# Generated by Django 2.2 on 2019-04-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.TextField()),
                ('name', models.TextField()),
                ('price', models.CharField(max_length=7)),
                ('cebulions', models.IntegerField()),
                ('category_id', models.CharField(max_length=10)),
            ],
        ),
    ]
